using System.Linq;
using Content.Shared._DV.Preferences;
using Content.Shared._DV.Roles;
using Content.Shared.Clothing;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
namespace Content.Client._DV.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class AntagsTab : RoleTab<AntagCategoryPrototype, AntagPrototype>
{
    public AntagsTab()
    {
        RobustXamlLoader.Load(this);
        Refresh();
    }

    private (bool, FormattedMessage?) GetIsAntagLocked(AntagPrototype antag)
    {
        var locked = !RequirementsManager.IsAllowed(antag, Profile, out var reason);
        return (locked, reason);
    }

    protected override Control CategoryContainer => RoleList;

    protected override IEnumerable<AntagPrototype> GetRolePrototypes(AntagCategoryPrototype category)
    {
        return category.Roles
            .Select(antagId => PrototypeManager.TryIndex(antagId, out var prototype) ? prototype : null)
            .Where(antag => antag is
                            {
                                SetPreference: true
                            }
                            && antag.VisibleProfileFactions.Contains(Profile?.Faction ?? CharacterProfileFaction.Crew))
            .Cast<AntagPrototype>()
            .Order(AntagUIComparer.Instance);
    }

    protected override IEnumerable<AntagCategoryPrototype> GetCategoryPrototypes()
    {
        return PrototypeManager
            .EnumeratePrototypes<AntagCategoryPrototype>()
            .Where(category => !category.EditorHidden)
            .Order(AntagCategoryUIComparer.Instance);
    }

    protected override RoleListEntry CreateEntry(AntagPrototype antag)
    {
        var texture = !string.IsNullOrWhiteSpace(antag.Icon) && PrototypeManager.TryIndex(antag.Icon, out var iconProto)
            ? SpriteSystem.Frame0(iconProto.Icon)
            : null;
        
        var (locked, reason) = GetIsAntagLocked(antag);
        var localizedObjective = Loc.GetString(antag.Objective);

        var choice = new RoleListEntry
        {
            Title = Loc.GetString(antag.Name),
            Description = string.IsNullOrWhiteSpace(localizedObjective) ? FormattedMessage.Empty : FormattedMessage.FromMarkupOrThrow(localizedObjective),
            IconTexture = texture,
            GuidebookEntries = antag.Guides,
            Locked = locked,
            LockedReason = reason ?? FormattedMessage.Empty
        };

        choice.OnOpenGuidebook += OnGuidebooksOpened;
        choice.OnRoleToggled += selected =>
        {
            if (Entries.TryGetValue(antag, out var list))
            {
                foreach (var entry in list)
                {
                    entry.SetSelected(selected);
                }
            }

            OnRoleToggled(new RoleToggledEventArgs(antag, selected));
        };

        if (!PrototypeManager.TryIndex(LoadoutSystem.GetAntagLoadoutPrototype(antag), out var roleLoadoutProto))
        {
            choice.LoadoutsDisabled = true;
        }
        else
        {
            choice.OnLoadoutButtonPressed += () =>
            {
                OnLoadoutOpened(new LoadoutOpeningEventArgs(antag, roleLoadoutProto));
            };
        }
        return choice;
    }

    protected override RoleCategory CreateCategory(AntagCategoryPrototype category)
    {
        var categoryName = Loc.GetString(category.Name);
        var categoryTooltip = Loc.GetString(category.Description);

        return new RoleCategory
        {
            CategoryName = Loc.GetString("character-profile-antags-category-title-format", ("name", categoryName)),
            CategoryTooltip = FormattedMessage.FromMarkupOrThrow(categoryTooltip),
            AccentColor = category.Color
        };
    }

    protected override void UpdateSelectedRoles()
    {
        foreach (var (proto, items) in Entries)
        {
            var value = Profile is not null
                        && Profile.AntagPreferences.Contains(proto);

            foreach (var entry in items)
            {
                entry.SetSelected(value);
            }
        }
    }
}
