using System.Linq;
using Content.Shared._DV.Preferences;
using Content.Shared.Clothing;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._DV.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class JobsTab : RoleTab<DepartmentPrototype, JobPrototype>
{
    protected override Control CategoryContainer => RoleList;
    
    public JobsTab()
    {
        RobustXamlLoader.Load(this);
        Refresh();
    }

    private (bool, FormattedMessage?) GetIsJobLocked(JobPrototype job)
    {
        var locked = !RequirementsManager.IsAllowed(job, Profile, out var reason);
        return (locked, reason);
    }

    protected override IEnumerable<JobPrototype> GetRolePrototypes(DepartmentPrototype department)
    {
        return department.Roles
            .Select(jobId => PrototypeManager.TryIndex(jobId, out var prototype) ? prototype : null)
            .Where(job => job is
                          {
                              SetPreference: true
                          }
                          && job.VisibleProfileFactions.Contains(Profile?.Faction ?? CharacterProfileFaction.Crew))
            .Cast<JobPrototype>()
            .Order(JobUIComparer.Instance);
    }
    
    protected override IEnumerable<DepartmentPrototype> GetCategoryPrototypes()
    {
        return PrototypeManager
            .EnumeratePrototypes<DepartmentPrototype>()
            .Where(d => !d.EditorHidden)
            .Order(DepartmentUIComparer.Instance);
    }
    
    protected override RoleListEntry CreateEntry(JobPrototype job)
    {
        var texture = !string.IsNullOrWhiteSpace(job.Icon) &&  PrototypeManager.TryIndex(job.Icon, out var jobIcon) 
            ? SpriteSystem.Frame0(jobIcon.Icon) 
            : null;
        
        var (locked, lockedReason) = GetIsJobLocked(job);

        var choice = new RoleListEntry
        {
            Title = job.LocalizedName,
            Description = string.IsNullOrWhiteSpace(job.LocalizedDescription) ? FormattedMessage.Empty : FormattedMessage.FromMarkupOrThrow(job.LocalizedDescription),
            IconTexture = texture,
            GuidebookEntries = job.Guides,
            Locked = locked,
            LockedReason = lockedReason ?? FormattedMessage.Empty,
        };

        choice.OnOpenGuidebook += OnGuidebooksOpened;
        choice.OnRoleToggled += selected =>
        {
            if (Entries.TryGetValue(job, out var list))
            {
                foreach (var entry in list)
                {
                    entry.SetSelected(selected);
                }
            }

            OnRoleToggled(new RoleToggledEventArgs(job, selected));
        };

        if (!PrototypeManager.TryIndex<RoleLoadoutPrototype>(LoadoutSystem.GetJobPrototype(job.ID), out var roleLoadoutProto))
        {
            choice.LoadoutsDisabled = true;
        }
        else
        {
            choice.OnLoadoutButtonPressed += () =>
            {
                OnLoadoutOpened(new LoadoutOpeningEventArgs(job, roleLoadoutProto));
            };
        }
        return choice;
    }
    
    protected override RoleCategory CreateCategory(DepartmentPrototype department)
    {
        var deptName = Loc.GetString(department.Name);
        
        return new RoleCategory
        {
            CategoryName = Loc.GetString("humanoid-profile-editor-department-jobs-label", ("departmentName", deptName)),
            CategoryTooltip = FormattedMessage.FromMarkupOrThrow(
                Loc.GetString("humanoid-profile-editor-jobs-amount-in-department-tooltip", ("departmentName", deptName))),
            AccentColor = department.Color
        };
    }
    
    protected override void UpdateSelectedRoles()
    {
        foreach (var (proto, items) in Entries)
        {
            var value = Profile is not null
                        && Profile.JobPriorities.TryGetValue(proto, out var priority)
                        && priority > JobPriority.Never;
            
            foreach (var entry in items)
            {
                entry.SetSelected(value);
            }
        }
    }
}