using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._DV.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class RoleCategory : BoxContainer
{
    private readonly StyleBoxFlat _accentBox = new()
    {
        BackgroundColor = Color.White
    };
    
    private bool _isExpanded;

    [PublicAPI]
    public string? CategoryName
    {
        get => CategoryNameLabel.Text;
        set => CategoryNameLabel.Text = value;
    }
    
    [PublicAPI]
    public FormattedMessage? CategoryTooltip { get; set; }

    [PublicAPI]
    public Color AccentColor
    {
        get => _accentBox.BackgroundColor;
        set => _accentBox.BackgroundColor = value;
    }

    public RoleCategory(bool defaultExpanded = true)
    {
        RobustXamlLoader.Load(this);
        HeaderButton.OnPressed += _ => ToggleExpanded();
        HeaderButton.TooltipSupplier = BuildTooltip;
        
        AccentBar.PanelOverride = _accentBox;
        
        _isExpanded = defaultExpanded;
        UpdateExpandedState();
    }

    [PublicAPI]
    public void AddItem(Control item) => Contents.AddChild(item);

    [PublicAPI]
    public void RemoveItem(Control item) => Contents.RemoveChild(item);
    
    private Tooltip? BuildTooltip(Control sender)
    {
        if (CategoryTooltip is not {} message) return null;

        var tooltip = new Tooltip();
        tooltip.SetMessage(message);
        return tooltip;
    }
    
    private void ToggleExpanded()
    {
        _isExpanded = !_isExpanded;
        UpdateExpandedState();
    }

    private void UpdateExpandedState()
    {
        ContentPanel.Visible = _isExpanded;
        ExpandIcon.Text = _isExpanded ? "▼" : "▶";
    }
}
