using Content.Shared.Guidebook;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DV.Lobby.UI.Roles;

[GenerateTypedNameReferences]
public sealed partial class RoleListEntry : PanelContainer
{
    [PublicAPI]
    public string? Title
    {
        get => RoleName.Text;
        set => RoleName.Text = value;
    }

    [PublicAPI]
    public FormattedMessage Description
    {
        get;
        set
        {
            if (field == value) 
                return;
            
            field = value;
            InvalidateMeasure();
        }
    } = FormattedMessage.Empty;

    [PublicAPI]
    public Texture? IconTexture
    {
        get => Icon.Texture;
        set => Icon.Texture = value;
    }

    [PublicAPI]
    public List<ProtoId<GuideEntryPrototype>>? GuidebookEntries
    {
        get;
        set
        {
            if (field == value) 
                return;
            
            field = value;
            InvalidateMeasure();
        }
    }

    [PublicAPI]
    public bool Locked
    {
        get;
        set
        {
            if (field == value) 
                return;

            field = value;
            UpdateLocked();
            InvalidateMeasure();
        }
    }

    [PublicAPI]
    public FormattedMessage LockedReason
    {
        get;
        set
        {
            if (field == value)
                return;

            field = value;
            InvalidateMeasure();
        }
    } = FormattedMessage.Empty;

    [PublicAPI]
    public bool LoadoutsDisabled
    {
        get => LoadoutButton.Disabled;
        set => LoadoutButton.Disabled = value;
    }

    [PublicAPI]
    public event Action<bool>? OnRoleToggled;

    [PublicAPI]
    public event Action? OnLoadoutButtonPressed;

    [PublicAPI]
    public event Action<List<ProtoId<GuideEntryPrototype>>>? OnOpenGuidebook;

    [PublicAPI]
    public bool IsSelected => RoleCheckbox.Pressed;

    public RoleListEntry()
    {
        RobustXamlLoader.Load(this);

        LoadoutButton.OnPressed += HandleLoadoutPressed;
        GuidebookButton.OnPressed += HandleGuidebookPressed;
        RoleCheckbox.OnToggled += HandleRoleToggled;
        
        TooltipSupplier = HandleTooltip;
    }

    public void SetSelected(bool selected)
    {
        RoleCheckbox.Pressed = selected && !Locked;
        UpdateStyles();
    }
    
    private void HandleRoleToggled(BaseButton.ButtonToggledEventArgs obj)
    {
        if (Locked)
        {
            RoleCheckbox.Pressed = false;
            return;
        }
        
        OnRoleToggled?.Invoke(RoleCheckbox.Pressed);
        UpdateStyles();
    }

    private void HandleLoadoutPressed(BaseButton.ButtonEventArgs _)
    {
        OnLoadoutButtonPressed?.Invoke();
    }
    
    private void HandleGuidebookPressed(BaseButton.ButtonEventArgs _)
    {
        if (GuidebookEntries is null || GuidebookEntries.Count == 0) return; 
        
        OnOpenGuidebook?.Invoke(GuidebookEntries);
    }

    private Tooltip? HandleTooltip(Control sender)
    {
        if (LockedReason.IsEmpty && Description.IsEmpty)
            return null;
        
        var tooltip = new Tooltip();

        if (Locked && !LockedReason.IsEmpty)
        {
            tooltip.SetMessage(LockedReason);
        }
        else if (!Description.IsEmpty)
        {
            tooltip.SetMessage(Description);
        }

        return tooltip;
    }
    
    private void UpdateLocked()
    {
        LockIcon.Visible = Locked;
        RoleCheckbox.Visible = !Locked;
        
        if (Locked && IsSelected)
        {
            SetSelected(false);
            OnRoleToggled?.Invoke(false);
        }

        UpdateStyles();
    }
    
    private void UpdateStyles()
    {
        if (RoleCheckbox.Pressed)
            AddStyleClass("TraitsEntrySelected");
        else
            RemoveStyleClass("TraitsEntrySelected");
        
        if (Locked)
            AddStyleClass("TraitsEntryDisabled");
        else
            RemoveStyleClass("TraitsEntryDisabled");
    }
}

